<div id = "logo">
<a href="/"><img src = "/static/images/logo.png" height = "80"/></a>
</div>
<div id = "navbar">
    <div id = "navheadobj">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	 <div id = "title">
    <i><a href="/"><img src = "/static/images/title.png"</a></i>
	 </div>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <div id = "onbar"><img src = "/static/images/activity.gif"></div>
    

    
    
    
<div id = "navbarfill">

<div id = "navobj">
<i><a href="/plugins/"><font color = "white">Modules</font>&nbsp;<img src="/static/images/down.png"></a></i>
&nbsp;&nbsp;&nbsp;
</div>
<div id = "navobj">
<i><a href="/settings/"><font color = "white">Settings</font>&nbsp;<img src="/static/images/down.png"></a></i>
</div>
<div id = "navpwnobj">
<a href="#dialog" name="startpwn">
<div = "startpwn" id = "startpwn"><i><font color = "yellow">Start</font></i></div>
</a>
</div>
<div id = "navpwnobj">
<a href="#dialog" name="stoppwn">
<div = "stoppwn" id = "stoppwn"><i><font color = "red">Stop</font></i></div>
</a>
</div>

</div></div>

<!--    NOTIFICATIONS      -->
    <div id = "notificationbox"><b><font color = "white"></font><div id = "notificationboxtitle"></div></b></font><div id = "notificationboxmessage"></div></div>
<!--    END_NOTIFICATIONS  -->

<!--    FOOTER      -->
    {% include "includes/footer.inc" %}
<!--    END_FOOTER  -->
